# Generated by Django 3.2.5 on 2022-05-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_post_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Post2',
        ),
    ]
